spring:
  thymeleaf:
    prefix: classpath:templates/**
    suffix: .html
    cache: false
  mvc:
    static-path-pattern: classpath:static/**
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
  profiles:
    active: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  security:
    user:
      name: admin
      password: admin

server:
  port: 8888