spring:
#  thymeleaf:
#    mode: HTML
#    encoding: UTF-8
#    check-template-location: true
#    prefix: classpath:/templates/
#    suffix: .html
#    cache: false
  mustache:
    charset: UTF-8
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .mustache
    cache: false
  mvc:
    static-path-pattern: /static/**
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
      show_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  profiles:
    active: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  security:
    user:
      name: admin
      password: admin
      roles:
        - ADMIN
        - USER

server:
  port: 8888