spring:
  config:
    import:
      - optional:classpath:/application-gitlab.yml
      - optional:classpath:/application-oauth.yml
      - optional:classpath:/application-google.yml
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  mvc:
    static-path-pattern: /static/**
    throw-exception-if-no-handler-found: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
      show_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  profiles:
    active: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1;MODE=MYSQL
    username: sa
    password:
  security:
    user:
      name: admin
      password: admin
      roles:
        - ADMIN
        - USER
server:
  port: 8888
logging:
  level:
    root: "info"
    com.swlab.dashboard.controller: "debug"
springdoc:
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
  paths-to-match:
    - /api/v1/**